### ISSUE TITLE
Test on Linux distros

### ISSUE THREAD

**Issue by chriswales95** [chriswales95/GitHero-CLI#23]

**Comment by ashfaq1934** [comment]
Tested on Ubuntu 19.10 (Eoan Ermine)

Deliverables:

- [ ] Configure Githero and add github api token through command line
- [ ] List all repositories, List a limited number of repositories 
- [ ] List gists
- [ ] List issues
- [ ] List pull requests

**Comment by chriswales95** [comment]
@ashfaq1934 Least it doesn't seem to have any problems running on Ubuntu :)

**Comment by chriswales95** [comment]
#38 mentioned here too

**Comment by chriswales95** [comment]
@ashfaq1934 We could probably close this soon after testing against some different Linux variants using something like Docker

**Comment by ashfaq1934** [comment]
@chriswales95  We should probably test main distributions like Arch, Debian Fedora. I think the distributions we should test are: 

- Ubuntu (Debian based, which we've already tested) 

- Manjaro (Arch based)

- Fedora

Those three should be enough.
