### ISSUE TITLE
Listing issues returns a promise error

### ISSUE THREAD

**Issue by ashfaq1934** [chriswales95/GitHero-CLI#38]
Listing issues from a repository returns an error even when there are issues within the repo. Occurs on both Windows and Linux.

![Screenshot from 2020-05-14 13-01-28](https://user-images.githubusercontent.com/46718979/81933110-bf224e00-95e4-11ea-97d3-db3607338a3a.png)

Returns a promise error on the getIssuesFromRepo function in Github.js.

**Comment by chriswales95** [comment]
@ashfaq1934 are you using the latest stuff from development?

**Comment by ashfaq1934** [comment]
@chriswales95 Yup, this is an on the development branch and the master branch

**Comment by chriswales95** [comment]
@ashfaq1934 Doesn't look recent because of the --raw tag. That's gone now in favour of the --format parameter. Try pulling again?

**Comment by ashfaq1934** [comment]
> @ashfaq1934 Doesn't look recent because of the --raw tag. That's gone now in favour of the --format parameter. Try pulling again?

still there

**Comment by ashfaq1934** [comment]
@chriswales95  is this an issue on Mac OS?

**Comment by ashfaq1934** [comment]
> @ashfaq1934 No doesn't seem so. Maybe reclone to confirm?

@chriswales95  still exists, I'll assign it to myself since it doesn't show up for you

**Comment by ashfaq1934** [comment]
Got this error when using the --unhadled restrictions=strict option
![Screenshot from 2020-06-05 15-09-00](https://user-images.githubusercontent.com/46718979/83917743-4d669b80-a76f-11ea-925f-f9d505517e06.png)

After running a test script i made using axios I got this error message in the response
![Screenshot from 2020-06-05 20-17-31](https://user-images.githubusercontent.com/46718979/83917849-7edf6700-a76f-11ea-835f-2dfabe823376.png)

Repository was undefined in the response object because I hadn't enabled the user permissions in the access token, after enabling this, the issue was gone.
![Screenshot from 2020-06-05 20-26-54](https://user-images.githubusercontent.com/46718979/83918019-cd8d0100-a76f-11ea-86b7-cc152ab4b6a0.png)

Returning the error message in the response should help resolve access issues like this
